apiVersion: v1
kind: Service
metadata:
  name: customer-support-service
  namespace: secure-customer-support
spec:
  selector:
    app: customer-support-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
